name: Build New Version

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-app:
    runs-on: macos-13

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Xcodebuild
        run: xcodebuild -project "Rename Everything.xcodeproj" -scheme "Rename Everything" -destination platform=macOS build -derivedDataPath ./build
      
      - name: Create zip file
        run: cp -r "build/Build/Products/Debug/Rename Everything" . && zip -r RenameEverything.zip renameEverything

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: RenameEverything.zip
